version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRE_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRE_DB:-fantastic_four}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRE_USERNAME:-postgres} -d ${POSTGRE_DB:-fantastic_four}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-networks

  nodejs:
    build: .
    container_name: fantastic-four-app
    env_file: .env
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgres://${POSTGRE_USERNAME:-postgres}:${POSTGRE_PASSWORD:-password}@db:5432/${POSTGRE_DB:-fantastic_four}
      - METRICS_ENABLED=true  # Tetap enable metrics untuk konsistensi
    ports:
      - "4000:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-networks
    # Labels untuk consistency (optional)
    labels:
      - "prometheus.scrape=true"
      - "prometheus.port=3000"
      - "prometheus.path=/metrics"

networks:
  app-networks:
    driver: bridge

volumes:
  pgdata: