apiVersion: apps/v1
kind: Deployment
metadata:
  name: fantastic-four-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fantastic-four
  template:
    metadata:
      labels:
        app: fantastic-four
    spec:
      containers:
        - name: nodejs-container
          image: alexandraqwz/fantastic_four:latest
          resources:           # WAJIB ADA AGAR HPA JALAN
            requests:
              cpu: "100m"      # Jatah CPU minimum (0.1 core)
            limits:
              cpu: "400m"
          ports:
            - containerPort: 3000
          env:
            
            - name: NODE_ENV
              value: "development"

            # Mengambil Username dari Secret
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret # Nama yang ada di metadata secret.yaml
                  key: POSTGRES_USER # Nama kunci di dalam data secret.yaml
            
            # Mengambil Password dari Secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_PASSWORD
            
            # Mengambil DATABASE dari Secret
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: POSTGRES_DB

            # Membuat DATABASE_URL secara dinamis
            - name: DATABASE_URL
              value: "postgresql://$(POSTGRES_USERNAME):$(POSTGRES_PASSWORD)@db:5432/$(POSTGRES_DB)"