apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  # Masukkan nilai hasil Base64 tadi di sini
  POSTGRES_USER: Y2Fsdmlu
  POSTGRES_PASSWORD: bmlraXRhd2lsbHk=
  POSTGRES_DB: cG9zdGdyZXM=  # Contoh Base64 dari 'db_utama'